export const CURRENT_WEATHER_REQUEST = "CURRENT_WEATHER_REQUEST";
export const CURRENT_WEATHER_SUCCESS = "CURRENT_WEATHER_SUCCESS";
export const CURRENT_WEATHER_FAILED = "CURRENT_WEATHER_FAILED";
export const CHANGE_CITY_REQUEST = "CHANGE_CITY_REQUEST";
export const OTHER_DAYS_REQUEST = "OTHER_DAYS_REQUEST";
export const OTHER_DAYS_SUCCESS = "OTHER_DAYS_SUCCESS";
export const OTHER_DAYS_FAILED = "OTHER_DAYS_FAILED";